# Uncomment and fill in the platforms you want to use.
# See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

# github: [z3rco]
# ko_fi: # username
# buy_me_a_coffee: # username
# custom: ["https://example.com/donate"]
